DEFAULT_TRACES_INPUT = '../../scream2000/traces/'
DEFAULT_TRACE_NAME_PREFIX = 'wave'
DEFAULT_VALUES_INPUT = '../../scream2000/values.csv'
DEFAULT_KEY_INPUT = '../../scream2000/key.csv'

BYTE = 8
PLAINTEXT_LENGTH = 128
BYTES_IN_PLAINTEXT = PLAINTEXT_LENGTH / BYTE