DEFAULT_TRACES_INPUT = './Collect_Scream/traces/'
DEFAULT_TRACE_NAME_PREFIX = 'wave'
DEFAULT_VALUES_INPUT = './Collect_Scream/values.csv'
DEFAULT_KEY_INPUT = './Collect_Scream/key.csv'

BYTE = 8
PLAINTEXT_LENGTH = 128
BYTES_IN_PLAINTEXT = PLAINTEXT_LENGTH / BYTE
